### ISSUE TITLE
Errors detected with interlogix integration

### ISSUE THREAD

**Issue by farberm** [aficustree/homebridge-alarmdecoder-platform#32]
Thanks for the plugin.Great work, It is working but I get the following errors in the log file. Any fixes/help would be appreciated.

[37m[11/7/2021, 6:42:43 AM] [39m[36m[Alarm System][39m found 3 FRONT DOOR,from cache, skipping
[37m[11/7/2021, 6:42:43 AM] [39m[36m[Alarm System][39m found 4 LIVING R.WINDOW,from cache, skipping
[37m[11/7/2021, 6:42:43 AM] [39m[36m[Alarm System][39m found 5 MOTION DETECTOR,from cache, skipping
[37m[11/7/2021, 6:42:43 AM] [39m[36m[Alarm System][39m found 6 KIT. NOOK WINDOW,from cache, skipping
[37m[11/7/2021, 6:42:43 AM] [39m[36m[Alarm System][39m found 7 KIT. NOOK DOOR,from cache, skipping
[37m[11/7/2021, 6:42:43 AM] [39m[36m[Alarm System][39m found 8 SMOKE DETECTOR,from cache, skipping
[37m[11/7/2021, 6:42:43 AM] [39m[36m[Alarm System][39m found switch away from cache, skipping
[37m[11/7/2021, 6:42:43 AM] [39m[36m[Alarm System][39m found switch stay from cache, skipping
[37m[11/7/2021, 6:42:43 AM] [39m[36m[Alarm System][39m found switch night from cache, skipping
[37m[11/7/2021, 6:42:43 AM] [39m[36m[homebridge-alarmdecoder-platform][39m This plugin generated a warning from the characteristic 'Motion Detected': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.

Second issue/Error:
[37m[11/7/2021, 7:00:58 AM] [39m[36m[Alarm System][39m TypeError: Cannot set property 'faulted' of undefined
    at /usr/lib/node_modules/homebridge-alarmdecoder-platform/alarmsystems/interlogix.js:25:84
    at Array.forEach (<anonymous>)
    at Interlogix.getAlarmState (/usr/lib/node_modules/homebridge-alarmdecoder-platform/alarmsystems/interlogix.js:24:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at AlarmdecoderPlatform._getStateFromAlarm (/usr/lib/node_modules/homebridge-alarmdecoder-platform/index.js:242:13)
    at AlarmdecoderPlatform.getSwitchState (/usr/lib/node_modules/homebridge-alarmdecoder-platform/index.js:355:9)

**Comment by farberm** [comment]
I am getting one additional warning.

[11/13/2021, 9:58:23 AM] [homebridge-alarmdecoder-platform] This plugin generated a warning from the characteristic 'Motion Detected': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
