### ISSUE TITLE
Issue loading module in homebridge in  new install

### ISSUE THREAD

**Issue by nebduj** [aficustree/homebridge-alarmdecoder-platform#6]
Homebridge Error Log:
Load homebridge-alarmdecoder-platform.alarmdecoder-platform
[11/13/2019, 10:46:44 PM] TypeError: Cannot read property 'port' of null
    at new AlarmdecoderPlatform (/usr/lib/node_modules/homebridge-alarmdecoder-platform/index.js:16:28)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

Entry in config.json
	{
            "platform" : "alarmdecoder-platform",
            "name" : "Alarm System",
            "port" : "8888",
            "key" : "3ZZHVUAAHV3A",
            "stateURL" : "http://alarmdecoder.local:2222/api/v1/alarmdecoder",
            "zoneURL" : "http://alarmdecoder.local:2222/api/v1/zones",
            "setURL" : "http://alarmdecoder.local:2222/api/v1/alarmdecoder/send",
            "setPIN" : "1245",
            "panicKey" : "<S1>",
            "useSwitches" : ["panic","chime","away","stay","night"],
            "DSCorHoneywell" : "Honeywell",
            "chimeKey":"9",
        }
I believe the port in the URLs and ports are inconsistent, I just didn't change them from the example.  I only changed the "IP" to the host hame.

**Comment by nebduj** [comment]
issue is present even without modifying config.json.

**Comment by aficustree** [comment]
the json isn't valid in the example, take out the last comma. I'll update the documentation

**Comment by nebduj** [comment]
Thanks.  I feel silly for how much time I’ve spent trying to figure this out for a comma.

**Comment by aficustree** [comment]
my bad. jsonlint every time :-)

**Comment by nebduj** [comment]
What’s the default port I should be using?  I’m using your raspberry pi image and have a working app but I’m getting a connection refused now when starting homebridge

**Comment by aficustree** [comment]
the alarmdecoder app will need to send a notification to a URL and a port. Just make sure whatever you set in the app is the same as what you configure on the plugin and you should be fine

**Comment by nebduj** [comment]
The port field seems to be missing in the web UI

**Comment by nebduj** [comment]
I figured it out.  I just appended the port the the IP address.  192.x.x.x:2222  I was looking for an input field.
